fpath=( "$HOME/.zcompletions" "$HOME/.zfunctions" $fpath )

# The following lines were added by compinstall

zstyle ':completion:*' completer _expand _complete _ignored _approximate
zstyle ':completion:*' matcher-list 'm:{[:lower:][:upper:]}={[:upper:][:lower:]}'
zstyle :compinstall filename '/home/dustin/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall
# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
setopt appendhistory autocd extendedglob no_nomatch notify
unsetopt beep
bindkey -v
# End of lines configured by zsh-newuser-install

# Remove delay when switching vi modes
# https://www.johnhawthorn.com/2012/09/vi-escape-delays/#zsh
# 10ms for key sequences
KEYTIMEOUT=1
# End remove delay when switching vi modes

# Keybindings
bindkey -M vicmd "/" history-incremental-pattern-search-backward
bindkey -M vicmd "?" history-incremental-pattern-search-forward
# End of keybindings

# Aliases
if [ $commands[hub] ]; then
  eval "$(hub alias -s)"
fi

if [ $commands[bat] ]; then
  alias cat=bat
fi
# End aliases

# Manual completions setup
if [ $commands[kubectl] ]; then
  source <(kubectl completion zsh)
fi

if [ $commands[helm] ]; then
  source <(helm completion zsh)
fi
# End manual completions setup

# Configure fzf
export PATH=$PATH:~/.fzf/bin
[ -f ~/.fzf/shell/completion.zsh ] && source ~/.fzf/shell/completion.zsh

[ -f ~/.fzf/shell/key-bindings.zsh ] && source ~/.fzf/shell/key-bindings.zsh

export FZF_DEFAULT_COMMAND="fd --type file"

export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_CTRL_T_OPTS="--preview '[[ -f {} ]] && (bat --color always {} || cat {})'"
# End configure fzf

# Setup pure prompt
autoload -U promptinit
promptinit
prompt pure
# End of setup pure prompt

# Source scripts
source ~/.zscripts/z.sh
# End source scripts

# Setup nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
# End setup nvm

# Add git-gerrit to PATH
export PATH=$PATH:~/git-gerrit
# End add git-gerrit to PATH

# Add go to PATH
export PATH=$PATH:/usr/local/go/bin:~/go/bin
# use GO 11.1 Modules
export GO111MODULES=on
# End add go to PATH

# Setup zsh-autosuggestions
source ~/.zscripts/zsh-autosuggestions/zsh-autosuggestions.zsh
bindkey '^ ' autosuggest-accept
# End setup zsh-autosuggestions

# Setup zsh-syntax-highlighting
# This must be last in zshrc
source ~/.zscripts/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
# End setup zsh-syntax-highlighting
