---
- name: Previous tmux version
  ansible.builtin.debug:
    msg: "tmux version: {{ ansible_local.tmux.INSTALLED_tmux_version | default('None') }}"

- name: Install tmux build deps via ansible.builtin.apt
  ansible.builtin.apt:
    name:
      - bison
      - libevent-dev
      - libncurses-dev
      - pkg-config
      - gcc
      - build-essential
      - xdg-utils
  become: true

- name: Download tmux to /tmp/tmux
  ansible.builtin.unarchive:
    dest: /tmp
    remote_src: true
    src: https://github.com/tmux/tmux/releases/download/{{ tmux_version }}/tmux-{{ tmux_version }}.tar.gz
  when: ansible_local.tmux.INSTALLED_tmux_version|default('None') != tmux_version|string

- name: Run /tmp/tmux-*/configure
  ansible.builtin.command: sh ./configure
  args:
    chdir: /tmp/tmux-{{ tmux_version }}
  when: ansible_local.tmux.INSTALLED_tmux_version|default('None') != tmux_version|string

- name: Run community.general.system.make in /tmp/tmux-{{ tmux_version }}
  community.general.make:
    chdir: /tmp/tmux-{{ tmux_version }}
  when: ansible_local.tmux.INSTALLED_tmux_version|default('None') != tmux_version|string

- name: Run community.general.system.make install to install tmux
  community.general.make:
    chdir: /tmp/tmux-{{ tmux_version }}
    target: install
  become: true
  when: ansible_local.tmux.INSTALLED_tmux_version|default('None') != tmux_version|string

- name: Cleanup /tmp/tmux-{{ tmux_version }}
  ansible.builtin.file:
    path: /tmp/tmux-{{ tmux_version }}/
    state: absent

- name: Install xsel so tmux-yank works
  ansible.builtin.apt:
    name: xsel=*
  become: true

- name: Install gawk for tmux-fingers
  ansible.builtin.apt:
    name: gawk
  become: true

- name: Create /etc/ansible/facts.d/
  ansible.builtin.file:
    path: /etc/ansible/facts.d/
    state: directory
    mode: '0755'
  become: true

- name: Update tmux version fact
  ansible.builtin.template:
    dest: /etc/ansible/facts.d/tmux.fact
    force: true
    mode: 0755
    src: tmux.fact.j2
  become: true

- name: Create ~/.tmux/plugins directory
  ansible.builtin.file:
    path: ~/.tmux/plugins
    state: directory
    mode: '0755'

- name: Clone tmux package manager
  ansible.builtin.git:
    dest: ~/.tmux/plugins/tpm
    repo: https://github.com/tmux-plugins/tpm
    version: "v{{ tpm_version }}"

- name: Copy .tmux.conf to ~ directory
  ansible.builtin.copy:
    backup: true
    dest: ~/.tmux.conf
    src: tmux.conf
    mode: '0644'
  notify:
    - Install tmux plugins
