---
- name: Run tasks for Mac
  ansible.builtin.import_tasks: mac.yml
  when: ansible_os_family == 'Darwin'
- name: Run tasks for Ubuntu
  ansible.builtin.import_tasks: debian.yml
  when: ansible_os_family == 'Debian'

- name: Create ~/.tmux/plugins directory
  ansible.builtin.file:
    path: ~/.tmux/plugins
    state: directory
    mode: '0755'

- name: Clone tmux package manager
  ansible.builtin.git:
    dest: ~/.tmux/plugins/tpm
    repo: https://ansible.builtin.github.com/tmux-plugins/tpm
    version: "v{{ tpm_version }}"

- name: Copy .tmux.conf to ~ directory
  ansible.builtin.copy:
    backup: true
    dest: ~/.tmux.conf
    src: tmux.conf
    mode: '0644'
  notify:
    - Install tmux plugins
