fpath=( "$HOME/.zfunctions" $fpath )

# The following lines were added by compinstall

zstyle ':completion:*' completer _expand _complete _ignored _approximate
zstyle ':completion:*' matcher-list 'm:{[:lower:][:upper:]}={[:upper:][:lower:]}'
zstyle :compinstall filename '/home/dustin/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall
# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
setopt appendhistory autocd extendedglob nomatch notify
unsetopt beep
bindkey -v
# End of lines configured by zsh-newuser-install

# Keybindings
bindkey -M vicmd "/" history-incremental-pattern-search-backward
bindkey -M vicmd "?" history-incremental-pattern-search-forward
# End of keybindings

# Setup pure prompt
autoload -U promptinit
promptinit
prompt pure
# End of setup pure prompt

# Source scripts
source ~/.zscripts/z.sh
# End source scripts

# Setup nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
# End setup nvm

# Setup zsh-syntax-highlighting
# This must be last in zshrc
source ~/.zscripts/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
# End setup zsh-syntax-highlighting
