---
- name: Run tasks for Mac
  ansible.builtin.import_tasks: mac.yml
  when: ansible_os_family == 'Darwin'

- name: Previous go version
  ansible.builtin.shell: |
    set -o pipefail

    if command -v /usr/local/go/bin/go > /dev/null ; then
      /usr/local/go/bin/go version | sed 's/.*go\(.*\) .*/\1/'
    fi
  args:
    executable: /bin/bash
  register: go_version
  changed_when: false

- name: Delete previous version of go to prevent corrupt go installation
  ansible.builtin.file:
    path: /usr/local/go
    state: absent
  when: go_version.stdout|default('None') != go_version|quote
  become: true

- name: Download and extract go to /usr/local/go
  ansible.builtin.unarchive:
    dest: /usr/local/
    remote_src: true
    src: https://dl.google.com/go/go{{ go_version }}.{{ ansible_system }}-amd64.tar.gz
  when: go_version.stdout|default('None') != go_version|quote
  become: true
