---
- name: Install gnupg2 so git ppa can be added
  ansible.builtin.apt:
    name:
      - gnupg2
  become: true

- name: Install vim via ansible.builtin.apt
  ansible.builtin.apt:
    name: "{{ packages }}"
  vars:
    packages:
      - vim=*
      - vim-gui-common=*
  become: true

- name: Copy .vimrc to ~ directory
  ansible.builtin.copy:
    backup: true
    dest: ~/.vimrc
    src: vimrc
    mode: '0644'
  notify:
    - Install vim plugins

- name: Create ~/.vim/autoload directory
  ansible.builtin.file:
    path: ~/.vim/autoload
    state: directory
    mode: '0755'

- name: Install vim-plug
  ansible.builtin.get_url:
    dest: ~/.vim/autoload/plug.vim
    mode: '0644'
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
