---
- name: Run tasks for Mac
  ansible.builtin.import_tasks: mac.yml
  when: ansible_os_family == 'Darwin'
- name: Run tasks for Ubuntu
  ansible.builtin.import_tasks: debian.yml
  when: ansible_os_family == 'Debian'

- name: Copy .vimrc to ~ directory
  ansible.builtin.copy:
    backup: true
    dest: ~/.vimrc
    src: vimrc
    mode: '0644'
  notify:
    - Install vim plugins

- name: Create ~/.vim/autoload directory
  ansible.builtin.file:
    path: ~/.vim/autoload
    state: directory
    mode: '0755'

- name: Install vim-plug
  ansible.builtin.get_url:
    dest: ~/.vim/autoload/plug.vim
    mode: '0644'
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
