---
- name: Run tasks for Mac
  ansible.builtin.import_tasks: mac.yml
  when: ansible_os_family == 'Darwin'
- name: Run tasks for Ubuntu
  ansible.builtin.import_tasks: debian.yml
  when: ansible_os_family == 'Debian'

- name: Copy .gitconfig to ~ directory
  ansible.builtin.copy:
    backup: true
    dest: ~/.gitconfig
    src: gitconfig
    mode: '0644'
