---
name: CI
on:
  - pull_request
jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        role:
          - fzf
          - git
          - go
          - hub
          - nvm
          - packages_system
          - tmux
          - vim
          - zsh
    steps:
      - uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0
      - env:
          LC_ALL: "C.UTF-8"
          LANG: "C.UTF-8"
          ROLE: "${{ matrix.role }}"
        run: |
          python3 --version
          python3 -m pip install pipenv
          export PATH=$HOME/.local/bin/:$PATH
          pipenv sync --dev
          pipenv run make ${ROLE}
...
