---
- name: Clone fzf repository
  ansible.builtin.git:
    dest: ~/.fzf
    repo: https://github.com/junegunn/fzf
    version: "{{ fzf_version }}"

- name: Download and extract fzf to ~/.fzf/bin/fzf
  ansible.builtin.unarchive:
    dest: ~/.fzf/bin/
    remote_src: true
    src: https://github.com/junegunn/fzf/releases/download/{{ fzf_version }}/fzf-{{ fzf_version }}-{{ ansible_system | lower }}_amd64.tar.gz
